// Code generated by "stringer -type=PermissionType -output permission_string.go"; DO NOT EDIT

package lara

import "fmt"

const _PermissionType_name = "ViewRecordEditRecordViewReportsEditProducts"

var _PermissionType_index = [...]uint8{0, 10, 20, 31, 43}

func (i PermissionType) String() string {
	if i < 0 || i >= PermissionType(len(_PermissionType_index)-1) {
		return fmt.Sprintf("PermissionType(%d)", i)
	}
	return _PermissionType_name[_PermissionType_index[i]:_PermissionType_index[i+1]]
}
