// Code generated by "stringer -type=TagType -output tag_string.go"; DO NOT EDIT

package lara

import "fmt"

const _TagType_name = "LyssaVirusTattooPetPassport"

var _TagType_index = [...]uint8{0, 10, 16, 27}

func (i TagType) String() string {
	if i < 0 || i >= TagType(len(_TagType_index)-1) {
		return fmt.Sprintf("TagType(%d)", i)
	}
	return _TagType_name[_TagType_index[i]:_TagType_index[i+1]]
}
