// Code generated by "stringer -type=objectType -output obj_string.go"; DO NOT EDIT

package http

import "fmt"

const _objectType_name = "ownerpatientrecordtitleunitgendercitystreetspeciesbreedtag"

var _objectType_index = [...]uint8{0, 5, 12, 18, 23, 27, 33, 37, 43, 50, 55, 58}

func (i objectType) String() string {
	if i < 0 || i >= objectType(len(_objectType_index)-1) {
		return fmt.Sprintf("objectType(%d)", i)
	}
	return _objectType_name[_objectType_index[i]:_objectType_index[i+1]]
}
